### ISSUE TITLE
dataset sample in demo video?

### ISSUE THREAD

**Issue by muhk01** [TreB1eN/InsightFace_Pytorch#112]
hello i'm currently also developing a face recognition system, i had already tried facenet but the result is not good enough, currently i am trying to compare precision between facenet and arcface, after tried code you provide and place registered face through facebank the result is still not as expected, would u mind if share face dataabase like youtube example you provide? because i already watched and precision is seem so high.

**Comment by ThanhPham1987** [comment]
me too
