### ISSUE TITLE
About the format of images: RGB or BGR?

### ISSUE THREAD

**Issue by doubbblek** [TreB1eN/InsightFace_Pytorch#141]
Hi, first of all, thanks for sharing this great repo! 
Currently, I am doing some experience with the provided pretrained weights. 

Here is the questions:
In infer_on_video, I see you did not transform BGR images (from cv2) to RGM format.
But in the data pipe, it seems like that you used PIL to load the image and as far as I know, this data type should be RGB instead of BGR.
So which one is the correct data type for your pretrained model?

Best Regards

**Comment by ruiming46zrm** [comment]
cv2_read == pil_read + blue_img
