### ISSUE TITLE
face_verfiy.py file always detect successfully even picture not match.

### ISSUE THREAD

**Issue by codulers** [TreB1eN/InsightFace_Pytorch#146]
I have setup InsightFace_Pytorch in PyCharm but whenever I run face_verify.py file it open the camera but always match with the facebank images and set lable Id_1.

Id_1 is the name of first sub-folder in facebank.

Even if facebank images are different then for which it is comparing but still it recognize successfully which is unexpected.

How Can I resolve this ?
Any suggestion is appreciated.
Thanks

**Comment by kaustubholpadkar** [comment]
How did you resolve this? @Ehtasha
