### ISSUE TITLE
Train problem :FileNotFoundError: [Errno 2] No such file or directory: 'D:\\InsightFace_Pytorch-master\\work_space\\log\\events.out.tfevents.1614916377.Wilbert-NB-W10'

### ISSUE THREAD

**Issue by w840401** [TreB1eN/InsightFace_Pytorch#168]
經過直接測試 是成功的!
不過在輸入 訓練指令時 
`python train.py -net mobilefacenet -b 200 -w 4`
出現以下錯誤
![失敗](https://user-images.githubusercontent.com/26362017/110065547-5e9a1280-7daa-11eb-9492-cab3496aeb9d.jpg)

請問該如何解決 感謝!

**Comment by chocokassy** [comment]
Hello, I encountered the same error, but I am running on linux, have you solved it?

**Comment by chocokassy** [comment]
I have solved it, you need to create a "log" folder in the work_space directory...
