### ISSUE TITLE
Learning rate

### ISSUE THREAD

**Issue by tensorboy** [TreB1eN/InsightFace_Pytorch#2]
Using the default learning rate 0.001 will not work on my side. 

Just let you know that I tried 0.01 and that number worked very well. :)

**Comment by tensorboy** [comment]
Yeah, it is 100, right?

**Comment by TreB1eN** [comment]
that Depends on the model and Gpu you are using,  on my 1080Ti, ir_se50 model uses batchsize 100,

**Comment by tensorboy** [comment]
Great, thanks for your information. I changed it to 200 and retraining now.

**Comment by TreB1eN** [comment]
closing
