### ISSUE TITLE
No such file or directory: 'data/facebank/names.npy

### ISSUE THREAD

**Issue by zhanglaplace** [TreB1eN/InsightFace_Pytorch#20]
python face_verify.py occur a error:
![image](https://user-images.githubusercontent.com/12178974/48936174-0924f900-ef45-11e8-98e2-07e1217ea7cd.png)

![image](https://user-images.githubusercontent.com/12178974/48936189-13df8e00-ef45-11e8-99d8-daa521fa2aa0.png)

**Comment by TreB1eN** [comment]
you need first prepare your face bank folder

**Comment by TreB1eN** [comment]
closing issue
