### ISSUE TITLE
What dataset was used for training IR-SE50 model?

### ISSUE THREAD

**Issue by Archelunch** [TreB1eN/InsightFace_Pytorch#30]
Hi! What dataset was used for training IR-SE50 model?  Is it VGGFace2?

**Comment by TreB1eN** [comment]
emore

**Comment by TreB1eN** [comment]
3.2.3 in Readme

**Comment by jgbradley1** [comment]
emore contains all datasets mentioned in section 2 of the README.

LFW, CFP-FF, CFP-FP, AgeDB-30, calfw, cplfw, vgg2_fp

Can more information be provided on how the the IR-SE50 model was trained and tested? If it was trained on all of these datasets, how were the performance metrics in section 2 calculated? What data was used in testing?
