### ISSUE TITLE
Environment setting problem(POSIXPATH error)

### ISSUE THREAD

**Issue by ming1144** [TreB1eN/InsightFace_Pytorch#4]
I've clone this code and run pip3 -r requirement.txt

But I met some problem due to invalid arguments

ex:  
os.path.join didn't support POSIXPATH

my environment is
ubuntu 16.0.4
python 3.5.1

**Comment by TreB1eN** [comment]
tell me which package cause the error

**Comment by TreB1eN** [comment]
I'm using Python3.6

**Comment by ming1144** [comment]
It seems to be a python version problem

I used python3.5 which is default version of Ubuntu 16.04
After using python3.6 problems seems to be gone
