### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by Po-Shin** [TreB1eN/InsightFace_Pytorch#49]
Hi, thanks for your great work. I would like to test if ArcFace works really well since eventually I need to use different network instead of ResNet/mobilenet. I would like to ask some questions, wish someone can answer me because I'm so confused now.

1. I downloaded the MS1M_85k_5.8M dataset, I am wondering if there's any preprocess steps such as MTCNN to crop the face or just directly feed the images into training?

2. I use my own face detector to crop the faces(remove the forehead) in both MS1M dataset(20k identities, 1.2M images) and LFW dataset off. When I used ResNet34(directly from torchvision.models) + ArcFace(s64, m=0.5, directly used yours). I only got 80% validation acc. However, when I trained on ResNet34+Center loss, I got 98% validation acc. Does it mean that Arcface can only perform well on full face?

Please help me out and if someone wants to make the test I please contact me and I will upload my dataset. (woo7952@gmail.com).

Thanks in advance

**Comment by TreB1eN** [comment]
1. the dataset is already well cropped
2. the answer is yes, when you run it on uncropped face, you need to first crop the face out through MTCNN like models,  this part is already implemented on this repo
