### ISSUE TITLE
MTCNN problem

### ISSUE THREAD

**Issue by kulkarniniraj** [TreB1eN/InsightFace_Pytorch#56]
MTCNN code changes in this repo compared to original TropComplique repo have reduced accuracy. I have checked that by replacing detector.py, first_stage.py and get_nets.py, I can improve accuracy significantly. Applies to mtcnn.py too. 

Any idea what could be causing this drop in accuracy?

**Comment by gunjunlee** [comment]
I suffered from same issue too. I finally found out the cause of the problem.
It's because of F.softmax() (at line 70, get_nets.py)
this repo sets dimension but not TropComplique's.
TropComplique's F.softmax implicitly choices dim=1 when this repo's dim is -1. this makes the difference.

**Comment by kulkarniniraj** [comment]
Thanks this works much better now. Hope this change is merged in this repo.

**Comment by kalenforn** [comment]
> I suffered from same issue too. I finally found out the cause of the problem.
> It's because of F.softmax() (at line 70, get_nets.py)
> this repo sets dimension but not TropComplique's.
> TropComplique's F.softmax implicitly choices dim=1 when this repo's dim is -1. this makes the difference.

I changed this value, but found that the accuracy is still not ideal. although it is better than before, but the MTCNN effect of Tensorflow version I have contacted is much better than this.
How can I modify the accuracy of the TF version?
Does anyone have a good way to slove this problem?
Thanks.

**Comment by engmubarak48** [comment]
> I suffered from same issue too. I finally found out the cause of the problem.
> It's because of F.softmax() (at line 70, get_nets.py)
> this repo sets dimension but not TropComplique's.
> TropComplique's F.softmax implicitly choices dim=1 when this repo's dim is -1. this makes the difference.

Thank you very much, the problem is solved now. @TreB1eN  explicitly chose dim=-1. removing it improves the performance for detection (MTCNN).

**Comment by kadirbeytorun** [comment]
While changing this dim value to 1 increases recall rate, it crashes the precision rate of mtcnn greatly. I believe TreB1eN made the right call by setting it as "-1"

**Comment by bokey007** [comment]
So what shold be done in this case since dim = -1 gives ValueError: need at least one array to concatenate and dim = 1 strike downs precision rate ? 

Need Help

**Comment by bokey007** [comment]
Also doing dim = 1 returns following error
IndexError: index 0 is out of bounds for axis 0 with size 0
