### ISSUE TITLE
What is ‘cpu_final.pth’?

### ISSUE THREAD

**Issue by WMQIAN** [TreB1eN/InsightFace_Pytorch#58]
Whether ‘cpu_final.pth’  means the pretrained model 'model_ir_se50.pth' ?
When I run face_verify.py，invalid file: WindowsPath('work_space/save/model_ir_se50.pth.pth')
I want to know if I made some mistakes.

Thanks for replying.

**Comment by youthM** [comment]
Hi, I met the same question, and how to solve it?

**Comment by knightlibra** [comment]
> Hi, I met the same question, and how to solve it?

Have you addressed this issue?

**Comment by wavesCHJ** [comment]
'mobilefacenet.pth' can also run in cpu，just modify the code in 'Learner.py', 82 lines，`self.model.load_state_dict(torch.load(save_path/'model_{}'.format(fixed_str), map_location=torch.device('cpu')))`

**Comment by wavesCHJ** [comment]
'mobilefacenet.pth' can also run in cpu，just modify the code in 'Learner.py', 82 lines，
`self.model.load_state_dict(torch.load(save_path/'model_{}'.format(fixed_str), map_location=torch.device('cpu')))`
don't forget to install the Pytorch version without cuda.
