### ISSUE TITLE
TypeError: invalid file: WindowsPath('work_space/save/model_ir_se50.pth')

### ISSUE THREAD

**Issue by WMQIAN** [TreB1eN/InsightFace_Pytorch#59]
When I run face_verify.py, the error occured.
Can you give me some advice?
Thanks for replying.

**Comment by njho** [comment]
Hi! @WMQIAN What was the solution?

**Comment by ThanhPham1987** [comment]
Hi @WMQIAN 
Please tell solution
Best regards,
PeterPham

**Comment by haoyu-bu** [comment]
For me, switching from Python 3.5 to Python 3.6 or later solved the problem. Check this [post](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t).
