### ISSUE TITLE
some questions to talk on evaluate and face_verify

### ISSUE THREAD

**Issue by ruiming46zrm** [TreB1eN/InsightFace_Pytorch#62]
1. why use Euclidean distance but not angular to calculate accurancy when evaluating lfw etc.

2. why use mean values of embeddings of one ID as class_centre when registering, with not l2_norm to put on the hypersphere

**Comment by nhatsmrt** [comment]
For 1, do you mean cosine similarity? I noticed that he normalized the embedding to 1. This means that the cosine similarity is equivalent to (squared) Euclidean distance, plus a constant.

**Comment by ruiming46zrm** [comment]
> For 1, do you mean cosine similarity? I noticed that he normalized the embedding to 1. This means that the cosine similarity is equivalent to (squared) Euclidean distance, plus a constant.

thank you very much, i get it
