### ISSUE TITLE
something strange when unpacking dataset

### ISSUE THREAD

**Issue by Walstruzz** [TreB1eN/InsightFace_Pytorch#75]
I download CASIA-Webface (10K ids/0.5M images) from [the original post](https://www.dropbox.com/s/lfluom5ybqqln02/faces_CASIA_112x112.zip?dl=0)

In script `data_pipe.py`, line 96, the image is saved by `PIL.Image`,which encoding image to `RGB`. I check the result after running `prepare_data.py`, most of the images are red. 

Obviously, modify `img = Image.fromarray(img)` to `img = Image.fromarray(img[:, :, ::-1])` would fix this problem, but I want to know if you design it deliberately, e.g., for post-processing or something else...

**Comment by Walstruzz** [comment]
* checkout: master, 350ff7a
* Python version: Anaconda, 3.6.5
* PIL version: 5.1.0
* MXNet version: 1.4.1

**Comment by Walstruzz** [comment]
I had already checked the images in `faces_emore/cfp_fp.bin`. The format of the image saved in this matrix is indeed `RGB`.

**Comment by niezhongliang** [comment]
> I had already checked the images in `faces_emore/cfp_fp.bin`. The format of the image saved in this matrix is indeed `RGB`.

thanks, I have met the same problem. Got solved by your tip.
