### ISSUE TITLE
prepare_data issue ext4 too many links

### ISSUE THREAD

**Issue by fmobrj** [TreB1eN/InsightFace_Pytorch#76]
Hello. 

Thanks for the gerat repo.

I am trying to load the emore data but I am facing the following message error:
- OSError: [Errno 31] Too many links: 'data/faces_emore/imgs/64998' 

I guess it have something to do with ext4 filesystem limits. Have anyone faced this issue? How did you solved it?

Thank you.

**Comment by TreB1eN** [comment]
I didn't encounter this issue

**Comment by fmobrj** [comment]
Thanks.
