### ISSUE TITLE
Do you need image alignment during training or evalution?

### ISSUE THREAD

**Issue by x7177214** [TreB1eN/InsightFace_Pytorch#8]
Thanks.

**Comment by x7177214** [comment]
I am also wondering what the dataset you used to pretrain Mobilefacenet? Thanks.

**Comment by TreB1eN** [comment]
yes, you can see from the codes, alignment is through MTCNN

**Comment by x7177214** [comment]
thanks

**Comment by x7177214** [comment]
I am also wondering what the dataset you used to pretrain Mobilefacenet. Thanks.

**Comment by TreB1eN** [comment]
emore dataset, I think it's a variation of MSCELEB, you can see more from this discussion

**Comment by TreB1eN** [comment]
https://github.com/deepinsight/insightface/issues/215

**Comment by x7177214** [comment]
Thanks.

**Comment by TreB1eN** [comment]
closing
