### ISSUE TITLE
In ArcFace your classnum is 51332, but the advice data emore is 85742.

### ISSUE THREAD

**Issue by foocker** [TreB1eN/InsightFace_Pytorch#85]
which data is 51332, or my understanding is wrong.

**Comment by eric-tc** [comment]
Hi i have the same question can you explain this to me please?

**Comment by Wblossom** [comment]
@eric-tc @foocker Hi, do you know the reason?

**Comment by Sunburst-zjr** [comment]
face_emore's classnum is 85742?
