### ISSUE TITLE
data form for evaluating

### ISSUE THREAD

**Issue by foocker** [TreB1eN/InsightFace_Pytorch#86]
how  change" agedb_30, agedb_30_issame = get_val_pair(data_path, 'agedb_30')"  for my own dataset (img fold and  labels).
len(agedb_30) = 12000, but len(agedb_30_issame)=6000, and sum(agedb_30_issame ) =3000, and is random. can you give some interpreation? thx.

**Comment by githubcyy** [comment]
@foocker hi, how do you evaluate the pretrained model? I use evaluate_model.ipynb, but something is wrong. 
"agedb_30, agedb_30_issame = get_val_pair(data_path, 'agedb_30')"
"def get_val_pair(path, name):
    carray = bcolz.carray(rootdir = path/name, mode='r')
    issame = np.load(path/'{}_list.npy'.format(name))
    return carray, issame"
there bcolz.carray() is wrong, no such file or directory.
i don't know why, can you give me some idea? thanks

**Comment by 2151330** [comment]
@githubcyy I have the same problem. Have you solved your problem

**Comment by foocker** [comment]
> 
> 
> @foocker hi, how do you evaluate the pretrained model? I use evaluate_model.ipynb, but something is wrong.
> "agedb_30, agedb_30_issame = get_val_pair(data_path, 'agedb_30')"
> "def get_val_pair(path, name):
> carray = bcolz.carray(rootdir = path/name, mode='r')
> issame = np.load(path/'{}_list.npy'.format(name))
> return carray, issame"
> there bcolz.carray() is wrong, no such file or directory.
> i don't know why, can you give me some idea? thanks

carray = bcolz.carray(rootdir = path/name, mode='r')
issame = np.load(path/'{}_list.npy'.format(name))
when you prepare_data.py to the faces_emore.zip, you will get form of bcolz file and *.npy file.
i'm curious about the evaluate function its self. the mapping of the data and its label. you know?

**Comment by foocker** [comment]
i guess 12000 contain 9000 same class image and 3000 diff class image  that random choose from the whole dataset, or 4500 pair same class and 1500 pair diff class img. is it right?@TreB1eN

i make some test, the image 12000, and label 6000, is not  corresponding with pairs, that is to say: when
agedb_30[200] is a other class img, but  agedb_30_issame[100] is True...., so how to correspond?

i will take more test, and the answer will be clear, thx...

right answer is: (0, 1 ), (2, 3), (4, 5) .... correspond label: 0, 1, 2 ...。3000 same pair 3000 diff pair, and the class  between same pair and same piar can be diff or same.
